#!/usr/bin/env python3
"""
Selkies Forge - build.py

Compiles everything in .source/src into the single, self-contained docker.sh
that people run with `curl ... | bash`, and proves it works before it says so.

    python3 .source/build.py                interactive: asks where to write docker.sh
    python3 .source/build.py -o ./docker.sh write there, no questions
    python3 .source/build.py --yes          write to the default (the repo's docker.sh)
    python3 .source/build.py --check        rebuild in memory and compare with docker.sh
    python3 .source/build.py --no-tests     skip the unit tests (the other checks still run)

What it checks, in order (any failure stops the build, nothing is written):

    1. Python    every module compiles, and the forge package imports cleanly
    2. Web UI    every JavaScript file parses (if node is installed), the HTML is there
    3. Data      every JSON file parses
    4. Shell     head.sh, tail.sh and the generated selkies-cli pass `bash -n`
    5. Layer     the forge layer's scripts and every built desktop's startwm.sh
                 pass `bash -n` / `sh -n`
    6. Payload   no file can break out of its heredoc, every file ends cleanly
    7. Script    the assembled docker.sh passes `bash -n`
    8. Unpack    docker.sh --extract-only unpacks every file byte for byte
    9. Engine    the unpacked engine answers --version and lists the catalog
   10. Tests     the unit tests in .source/tests (no desktops are started)

It only needs Python 3.8+ and bash. No network, no Docker, no root.

Selkies Forge is open source (MIT). Change anything you like, then run this.
"""

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src")
REPO = os.path.dirname(HERE)
DEFAULT_OUT = os.path.join(REPO, "docker.sh")

# ---------------------------------------------------------------- terminal
COLOR = sys.stdout.isatty() and os.environ.get("NO_COLOR") is None


def c(code, text):
    return "\033[%sm%s\033[0m" % (code, text) if COLOR else str(text)


def ok(msg):
    print("  %s %s" % (c("38;5;79", "✔"), msg))


def info(msg):
    print("  %s %s" % (c("38;5;75", "·"), msg))


def warn(msg):
    print("  %s %s" % (c("38;5;221", "!"), msg))


def fail(msg, detail=""):
    print("\n  %s %s" % (c("38;5;203", "✘"), c("1", msg)))
    for line in (detail or "").strip().splitlines()[-25:]:
        print("    " + c("2", line))
    print("\n  %s\n" % c("2", "nothing was written"))
    sys.exit(1)


def banner():
    art = [
        r"   ___ ___ _    _  _____ ___ ___   ___ ___  ___  ___ ___ ",
        r"  / __| __| |  | |/ /_ _| __/ __| | __/ _ \| _ \/ __| __|",
        r"  \__ \ _|| |__| ' < | || _|\__ \ | _| (_) |   / (_ | _| ",
        r"  |___/___|____|_|\_\___|___|___/ |_| \___/|_|_\\___|___|",
    ]
    cols = ["38;5;69", "38;5;75", "38;5;81", "38;5;117"]
    print()
    for line, col in zip(art, cols):
        print(c("1;" + col, line))
    print(c("2", "  build.py: compile .source/ into one docker.sh, then prove it works"))
    print()


def step(n, title):
    print(c("1;38;5;255", "\n  %2d  %s" % (n, title)))


def ask(prompt, default):
    try:
        ans = input("  %s %s [%s] " % (c("38;5;75", "?"), prompt, c("1", default))).strip()
    except EOFError:
        ans = ""
    return ans or default


def run(cmd, timeout=300, env=None, cwd=None):
    p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                       timeout=timeout, env=env, cwd=cwd)
    return p.returncode, p.stdout.decode("utf-8", "replace")


# ---------------------------------------------------------------- manifest
def manifest():
    """[(path inside app/, source path)] in a stable order. selkies-cli is generated."""
    files = [("engine.py", os.path.join(SRC, "engine.py"))]
    for name in sorted(os.listdir(os.path.join(SRC, "forge"))):
        if name.endswith(".py"):
            files.append(("forge/" + name, os.path.join(SRC, "forge", name)))
    for sub in ("web", "data"):
        for name in sorted(os.listdir(os.path.join(SRC, sub))):
            if not name.startswith("."):
                files.append(("%s/%s" % (sub, name), os.path.join(SRC, sub, name)))
    files.append(("selkies-cli", None))
    return files


def ident(path):
    return "".join(ch if ch.isalnum() else "_" for ch in path).upper()


def read_text(path):
    with open(path, "r", encoding="utf-8") as fh:
        text = fh.read()
    return text if text.endswith("\n") else text + "\n"


def gen_selkies_cli(head, tail):
    head_body = head.split("\n", 1)[1]
    return ("#!/usr/bin/env bash\n# selkies-cli front end, generated by build.py\n"
            "FORGE_AS_CLI=1\n" + head_body +
            "\n# The engine and UI were unpacked by docker.sh; nothing to extract here.\n"
            "extract_payload() {\n"
            "  if [ ! -f \"$FORGE_APP/engine.py\" ]; then\n"
            "    die \"Selkies Forge is not installed in $FORGE_HOME. Run: curl -fsSL $FORGE_URL | bash\"\n"
            "  fi\n"
            "}\n" + tail)


EXTRACT_HEAD = r'''# Writes the engine and UI into $FORGE_APP, but only when they changed.
extract_payload() {
  local stamp="$FORGE_APP/.payload"
  if [ "${FORCE_EXTRACT:-0}" != "1" ] && [ -f "$stamp" ] && \
     [ "$(cat "$stamp" 2>/dev/null)" = "$FORGE_PAYLOAD_SHA" ]; then
    return 0
  fi
  mkdir -p "$FORGE_APP/forge" "$FORGE_APP/web" "$FORGE_APP/data"
'''

EXTRACT_TAIL = r'''  chmod 755 "$FORGE_APP/selkies-cli" "$FORGE_APP/engine.py" 2>/dev/null
  if command -v sha256sum >/dev/null 2>&1; then
    local bad=0 f var
    for f in $FORGE_PAYLOAD_FILES; do
      var="FORGE_SHA_$(printf '%s' "$f" | tr -c 'A-Za-z0-9\n' '_' | tr '[:lower:]' '[:upper:]')"
      if [ "$(sha256sum "$FORGE_APP/$f" | cut -d' ' -f1)" != "${!var}" ]; then
        bad=1
        printf '  %s!%s %s did not extract cleanly\n' "$YEL" "$NC" "$f"
      fi
    done
    [ "$bad" = 1 ] && die "the embedded payload is damaged; re-download this script"
  fi
  # Files an older version shipped that this one does not (the engine used to
  # be a single engine.py). Only inside the forge's own app directory.
  if [ "$FORGE_APP" = "$FORGE_HOME/app" ]; then
    local keep=" $FORGE_PAYLOAD_FILES " rel
    while IFS= read -r f; do
      rel="${f#"$FORGE_APP"/}"
      case "$keep" in *" $rel "*) ;; *) rm -f -- "$f" ;; esac
    done < <(find "$FORGE_APP" -type f ! -name .payload ! -path '*/__pycache__/*' 2>/dev/null)
    find "$FORGE_APP" -type d -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null
    find "$FORGE_APP" -mindepth 1 -type d -empty -delete 2>/dev/null
  fi
  printf '%s' "$FORGE_PAYLOAD_SHA" > "$stamp"
}
'''


def assemble(contents, head, tail):
    """contents: [(app path, text)]. Returns the docker.sh text."""
    out = [head, "\n# =========================================================================\n"
           "#  embedded payload: the engine, the web UI and the selkies-cli front end\n"
           "#  (generated by .source/build.py; edit the files in .source/src instead)\n"
           "# =========================================================================\n\n"]
    for path, text in contents:
        out.append('FORGE_SHA_%s="%s"\n' % (ident(path), hashlib.sha256(text.encode()).hexdigest()))
    allsha = hashlib.sha256("".join(t for _, t in contents).encode()).hexdigest()
    out.append('FORGE_PAYLOAD_SHA="%s"\n' % allsha)
    out.append('FORGE_PAYLOAD_FILES="%s"\n\n' % " ".join(p for p, _ in contents))
    out.append(EXTRACT_HEAD)
    for path, text in contents:
        delim = "__FORGE_FILE_%s__" % ident(path)
        out.append("  cat > \"$FORGE_APP/%s\" <<'%s'\n" % (path, delim))
        out.append(text)
        out.append(delim + "\n")
    out.append(EXTRACT_TAIL)
    out.append(tail)
    return "".join(out), allsha


# ---------------------------------------------------------------- checks
def check_python(files):
    pys = [src for path, src in files if src and path.endswith(".py")]
    pys += [os.path.join(HERE, "tools", f) for f in sorted(os.listdir(os.path.join(HERE, "tools")))
            if f.endswith(".py")]
    for p in pys:
        try:
            with open(p, encoding="utf-8") as fh:
                compile(fh.read(), p, "exec")
        except SyntaxError as ex:
            fail("Python does not compile: %s" % os.path.relpath(p, REPO),
                 "line %s: %s\n%s" % (ex.lineno, ex.msg, (ex.text or "").rstrip()))
    env = dict(os.environ, FORGE_HOME=tempfile.mkdtemp(prefix="forge-build-"), FORGE_AUTO_UPDATE="0")
    code = ("import sys, importlib, pkgutil; sys.path.insert(0, %r)\n"
            "import forge\n"
            "for m in pkgutil.iter_modules(forge.__path__): importlib.import_module('forge.' + m.name)\n"
            "print(len(list(pkgutil.iter_modules(forge.__path__))))" % SRC)
    rc, out = run([sys.executable, "-c", code], env=env)
    shutil.rmtree(env["FORGE_HOME"], ignore_errors=True)
    if rc != 0:
        fail("the forge package does not import", out)
    ok("%d Python files compile; all %s engine modules import" % (len(pys), out.strip()))
    # pyflakes, when it is installed, catches names that are used but never
    # defined or imported: the bug a module split is most likely to cause.
    rc, out = run([sys.executable, "-m", "pyflakes", os.path.join(SRC, "forge"),
                   os.path.join(SRC, "engine.py")])
    if "No module named pyflakes" in out:
        info("pyflakes is not installed, so undefined names were not checked "
             "(pip install pyflakes)")
    else:
        bad = [l for l in out.splitlines()
               if "undefined name" in l or "unable to detect undefined names" in l
               or "redefinition of unused" in l]
        if bad:
            fail("pyflakes found real problems", "\n".join(bad))
        ok("pyflakes: no undefined names")


def check_web(files):
    js = [src for path, src in files if src and path.endswith(".js")]
    node = shutil.which("node")
    if node:
        for p in js:
            rc, out = run([node, "--check", p])
            if rc != 0:
                fail("JavaScript does not parse: %s" % os.path.relpath(p, REPO), out)
        ok("%d JavaScript files parse (node --check)" % len(js))
    else:
        warn("node is not installed, so JavaScript syntax was not checked")
    if not any(path == "web/index.html" for path, _ in files):
        fail("web/index.html is missing")


def check_json(files):
    n = 0
    for path, src in files:
        if src and path.endswith(".json"):
            try:
                with open(src) as fh:
                    json.load(fh)
                n += 1
            except ValueError as ex:
                fail("JSON does not parse: %s" % path, str(ex))
    ok("%d JSON data files parse" % n)


def bash_n(text, label, shell="bash"):
    with tempfile.NamedTemporaryFile("w", suffix=".sh", delete=False) as fh:
        fh.write(text)
        name = fh.name
    try:
        rc, out = run([shell, "-n", name])
    finally:
        os.unlink(name)
    if rc != 0:
        fail("%s has a shell syntax error" % label, out)


def check_layer():
    sys.path.insert(0, SRC)
    try:
        from forge import catalog, layer, recipes
    finally:
        sys.path.pop(0)
    n = 0
    for name in ("AGENT", "SEED", "XSETTINGSD_RUN", "AGENT_RUN"):
        bash_n(getattr(layer, name), "the forge layer's %s" % name.lower())
        n += 1
    bash_n(layer.BWRAP_SHIM, "the forge layer's bwrap shim", shell="sh")
    builds = [e for e in catalog.CATALOG if e["kind"] == "build"]
    for e in builds:
        bash_n(recipes.gen_startwm(e), "startwm.sh for %s" % e["id"])
        bash_n(recipes.gen_install_sh(e), "the install script for %s" % e["id"], shell="sh")
    ok("forge layer scripts (%d) and startwm/install scripts for %d built desktops pass"
       % (n + 1, len(builds)))


def check_payload(contents):
    for path, text in contents:
        delim = "__FORGE_FILE_%s__" % ident(path)
        if ("\n" + delim + "\n") in ("\n" + text):
            fail("%s contains its own heredoc terminator (%s)" % (path, delim))
    ok("%d payload files, no heredoc collisions" % len(contents))


def self_test(out_text, contents):
    tmp = tempfile.mkdtemp(prefix="forge-selftest-")
    try:
        script = os.path.join(tmp, "docker.sh")
        with open(script, "w") as fh:
            fh.write(out_text)
        app = os.path.join(tmp, "app")
        env = dict(os.environ, FORGE_HOME=os.path.join(tmp, "home"), FORGE_AUTO_UPDATE="0",
                   FORGE_BIN_DIR=os.path.join(tmp, "bin"), TERM="dumb")
        rc, out = run(["bash", script, "--extract-only", app], env=env, timeout=120)
        if rc != 0:
            fail("docker.sh --extract-only failed", out)
        for path, text in contents:
            p = os.path.join(app, path)
            if not os.path.isfile(p):
                fail("unpacking lost %s" % path)
            with open(p, encoding="utf-8") as fh:
                if fh.read() != text:
                    fail("unpacking changed %s" % path)
        ok("docker.sh unpacks all %d files byte for byte" % len(contents))
        rc, out = run([sys.executable, os.path.join(app, "engine.py"), "--version"], env=env)
        if rc != 0:
            fail("the unpacked engine does not start", out)
        version = out.strip()
        rc, out = run([sys.executable, os.path.join(app, "engine.py"), "list", "--format", "tsv"],
                      env=env, timeout=120)
        if rc != 0:
            fail("the unpacked engine cannot list the catalog", out)
        n = len([l for l in out.splitlines() if l.strip()])
        rc, out = run(["bash", os.path.join(app, "selkies-cli"), "--version"], env=env)
        if rc != 0:
            fail("the unpacked selkies-cli does not start", out)
        ok("unpacked engine %s lists %d desktops; selkies-cli answers (%s)"
           % (version, n, out.strip()))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def unit_tests():
    tests = os.path.join(HERE, "tests")
    env = dict(os.environ, PYTHONPATH=SRC, FORGE_HOME=tempfile.mkdtemp(prefix="forge-tests-"),
               FORGE_AUTO_UPDATE="0")
    t0 = time.time()
    rc, out = run([sys.executable, "-m", "unittest", "discover", "-s", tests, "-t", HERE],
                  env=env, timeout=900, cwd=HERE)
    shutil.rmtree(env["FORGE_HOME"], ignore_errors=True)
    if rc != 0:
        fail("unit tests failed", out)
    summary = [l for l in out.splitlines() if l.startswith("Ran ")]
    n = summary[-1].split()[1] if summary else "all"
    ok("%s tests passed (%.1fs)" % (n, time.time() - t0))


# ---------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser(description="Compile .source/ into docker.sh")
    ap.add_argument("-o", "--out", help="where to write docker.sh (asked if not given)")
    ap.add_argument("-y", "--yes", action="store_true", help="no questions; default output")
    ap.add_argument("--check", action="store_true",
                    help="build in memory and compare with the existing docker.sh")
    ap.add_argument("--no-tests", action="store_true", help="skip the unit tests")
    a = ap.parse_args()

    banner()
    interactive = sys.stdin.isatty() and not a.yes and not a.out and not a.check
    out_path = a.out or DEFAULT_OUT
    if interactive:
        print(c("2", "  This compiles every file in .source/src into one docker.sh.\n"))
        out_path = ask("Where should docker.sh be written?", os.path.relpath(DEFAULT_OUT))
    out_path = os.path.abspath(os.path.expanduser(out_path))
    if os.path.isdir(out_path):
        out_path = os.path.join(out_path, "docker.sh")

    files = manifest()
    with open(os.path.join(SRC, "shell", "head.sh")) as fh:
        head = fh.read()
    with open(os.path.join(SRC, "shell", "tail.sh")) as fh:
        tail = fh.read()
    head = head if head.endswith("\n") else head + "\n"
    # one version everywhere: head.sh, the engine, and the root forge-addon.json
    # (the forge as a Weft addon for Burrow)
    want = next((l.split('"')[1] for l in head.splitlines() if l.startswith("FORGE_VERSION=")), "?")
    with open(os.path.join(SRC, "forge", "paths.py")) as fh:
        eng = next((l.split('"')[1] for l in fh if l.startswith("VERSION = ")), "?")
    try:
        with open(os.path.join(os.path.dirname(HERE), "forge-addon.json")) as fh:
            addon_v = json.load(fh).get("version")
    except (OSError, ValueError):
        addon_v = want
    if not want == eng == addon_v:
        fail("versions disagree", "head.sh %s, paths.py %s, forge-addon.json %s" % (want, eng, addon_v))
    tail = tail if tail.endswith("\n") else tail + "\n"
    cli = gen_selkies_cli(head, tail)
    contents = [(p, read_text(s) if s else cli) for p, s in files]

    step(1, "Python")
    check_python(files)
    step(2, "Web UI")
    check_web(files)
    step(3, "Data")
    check_json(files)
    step(4, "Shell front end")
    bash_n(head, "head.sh")
    bash_n(tail, "tail.sh")
    bash_n(cli, "the generated selkies-cli")
    ok("head.sh, tail.sh and the generated selkies-cli pass bash -n")
    step(5, "Forge layer and desktop scripts")
    check_layer()
    step(6, "Payload")
    check_payload(contents)
    step(7, "Assemble")
    text, payload_sha = assemble(contents, head, tail)
    bash_n(text, "the assembled docker.sh")
    ok("docker.sh assembles and passes bash -n (%d KB, %d lines)"
       % (len(text) // 1024, text.count("\n")))
    step(8, "Unpack and run")
    self_test(text, contents)
    if a.no_tests:
        warn("unit tests skipped (--no-tests)")
    else:
        step(9, "Unit tests")
        unit_tests()

    if a.check:
        try:
            with open(out_path) as fh:
                same = fh.read() == text
        except OSError:
            same = False
        print()
        if same:
            ok("%s is up to date with .source/" % os.path.relpath(out_path))
            return 0
        fail("%s differs from what .source/ builds; run build.py to update it"
             % os.path.relpath(out_path))

    if interactive and os.path.exists(out_path):
        if ask("%s exists. Overwrite it?" % os.path.relpath(out_path), "y").lower()[:1] != "y":
            print("\n  %s\n" % c("2", "left as it was"))
            return 0
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    tmp = out_path + ".tmp"
    with open(tmp, "w") as fh:
        fh.write(text)
    os.chmod(tmp, 0o755)
    os.replace(tmp, out_path)

    version = next((l.split('"')[1] for l in head.splitlines() if l.startswith("FORGE_VERSION=")), "?")
    sha = hashlib.sha256(text.encode()).hexdigest()
    print()
    print("  " + c("1;38;5;79", "▰ BUILT") + "  " + c("2", "Selkies Forge %s" % version))
    print("  " + c("2", "─" * 64))
    print("  %s %s" % (c("2", "%-10s" % "output"), c("1;38;5;75", out_path)))
    print("  %s %d KB, %d lines, %d embedded files" % (c("2", "%-10s" % "size"), len(text) // 1024,
                                                        text.count("\n"), len(contents)))
    print("  %s %s" % (c("2", "%-10s" % "sha256"), sha))
    print("  %s %s" % (c("2", "%-10s" % "payload"), payload_sha[:16]))
    print()
    shown = os.path.relpath(out_path) if out_path.startswith(os.getcwd() + os.sep) else out_path
    print("  " + c("2", "Run it:  bash %s" % shown))
    print("  " + c("2", "This is open source (MIT): change anything you like and rebuild."))
    print()
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n  %s\n" % c("2", "stopped; nothing was written"))
        sys.exit(130)
