#!/usr/bin/env python3
"""Build-time fetch of real distro marks from Simple Icons (CC0), written to
src/web/brands.js. Colours too dark to read on the dark UI are lifted toward
white so every mark stays legible."""
import json, os, re, time, urllib.request

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src", "web", "brands.js")
SLUGS = {
    "ubuntu": "ubuntu", "debian": "debian", "fedora": "fedora", "arch": "archlinux",
    "alpine": "alpinelinux", "kali": "kalilinux", "parrot": "parrotsecurity",
    "almalinux": "almalinux", "rocky": "rockylinux", "centos": "centos",
    "opensuse": "opensuse", "mint": "linuxmint", "zorin": "zorin", "pop": "popos",
    "elementary": "elementary", "garuda": "garudalinux",
}
UA = "SelkiesForge/1.1 build"


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8")


def lum(hexc):
    r, g, b = (int(hexc[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def lift(hexc, amt):
    r, g, b = (int(hexc[i:i + 2], 16) for i in (0, 2, 4))
    f = lambda v: int(v + (255 - v) * amt)
    return "%02x%02x%02x" % (f(r), f(g), f(b))


def clean(svg):
    # Only the shapes: no scripts, handlers, titles or external refs.
    if re.search(r"<script|on\w+=|href=|xlink", svg, re.I):
        raise ValueError("unexpected content")
    svg = re.sub(r"<title>.*?</title>", "", svg, flags=re.S)
    svg = re.sub(r'\srole="img"', "", svg)
    return svg.replace("<svg ", '<svg aria-hidden="true" ', 1).strip()


out, report = {}, []
for fam, slug in SLUGS.items():
    svg = fetch("https://cdn.simpleicons.org/%s" % slug)
    m = re.search(r'fill="#([0-9A-Fa-f]{6})"', svg)
    color = m.group(1) if m else "ffffff"
    L = lum(color)
    # Hand-picked where the brand colour vanishes on a dark surface; reds like
    # Debian's read fine and turn pink if lightened, so they are left alone.
    override = {"alpine": "4a9ccc", "almalinux": "dfe5ee", "centos": "8f8fd6"}.get(fam)
    if override:
        new = override
        svg = fetch("https://cdn.simpleicons.org/%s/%s" % (slug, new))
        report.append("%-10s #%s -> #%s (lifted for contrast, lum %.2f)" % (fam, color, new, L))
        color = new
    else:
        report.append("%-10s #%s" % (fam, color))
    out[fam] = clean(svg)
    time.sleep(0.25)

with open(OUT, "w") as fh:
    fh.write("/* Real distro marks from Simple Icons (CC0 1.0, simpleicons.org).\n"
             "   Trademarks belong to their owners; shown only to identify each distro.\n"
             "   Generated by fetch_logos.py on %s. */\n" % time.strftime("%Y-%m-%d"))
    fh.write("window.FORGE_BRANDS = %s;\n" % json.dumps(out, indent=1))
print("\n".join(report))
print("wrote %s (%d marks, %d bytes)" % (OUT, len(out), os.path.getsize(OUT)))
