"""
Selkies Forge engine - recipes

Build recipes: install scripts, startwm.sh and Dockerfiles for built desktops.
"""

import base64
import re

from . import layer
from .paths import IPREFIX, LABEL, VERSION


INSTALL_SH = {
    "apt": """
export DEBIAN_FRONTEND=noninteractive
echo 'Acquire::Retries "6";' > /etc/apt/apt.conf.d/80-forge-retries
echo ">> forge: apt-get update"
for i in 1 2 3; do apt-get update -qq && break; echo ">> forge: apt-get update failed, retry $i"; sleep $((i * 5)); done
echo ">> forge: installing desktop packages"
if ! apt-get install -y --no-install-recommends $PKGS; then
  echo ">> forge: bulk install failed, falling back to one at a time"
  apt-get -f install -y || true
  for p in $PKGS; do
    apt-get install -y --no-install-recommends "$p" >/dev/null 2>&1 \\
      && echo ">> forge: ok   $p" || echo ">> forge: skip $p"
  done
fi
apt-get clean
rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/* /config/.cache 2>/dev/null || true
""",
    "dnf": """
echo ">> forge: installing desktop packages with dnf"
echo "retries=10" >> /etc/dnf/dnf.conf 2>/dev/null || true
if ! dnf install -y --setopt=install_weak_deps=False --skip-broken --skip-unavailable $PKGS; then
  echo ">> forge: bulk install failed, falling back to one at a time"
  for p in $PKGS; do
    dnf install -y --setopt=install_weak_deps=False "$p" >/dev/null 2>&1 \\
      && echo ">> forge: ok   $p" || echo ">> forge: skip $p"
  done
fi
dnf clean all
rm -rf /var/cache/dnf /tmp/* /config/.cache 2>/dev/null || true
""",
    "pacman": """
echo ">> forge: refreshing pacman keyring"
pacman -Sy --noconfirm --needed archlinux-keyring >/dev/null 2>&1 || true
pacman -Sy --noconfirm >/dev/null 2>&1 || true
echo ">> forge: installing desktop packages with pacman"
if ! pacman -S --noconfirm --needed $PKGS; then
  echo ">> forge: bulk install failed, falling back to one at a time"
  for p in $PKGS; do
    pacman -S --noconfirm --needed "$p" >/dev/null 2>&1 \\
      && echo ">> forge: ok   $p" || echo ">> forge: skip $p"
  done
fi
pacman -Scc --noconfirm >/dev/null 2>&1 || true
rm -rf /var/cache/pacman/pkg/* /tmp/* /config/.cache 2>/dev/null || true
""",
    "apk": """
echo ">> forge: installing desktop packages with apk"
for i in 1 2 3; do apk update >/dev/null 2>&1 && break; sleep $((i * 5)); done
if ! apk add --no-cache $PKGS; then
  echo ">> forge: bulk install failed, falling back to one at a time"
  for p in $PKGS; do
    apk add --no-cache "$p" >/dev/null 2>&1 \\
      && echo ">> forge: ok   $p" || echo ">> forge: skip $p"
  done
fi
rm -rf /var/cache/apk/* /tmp/* /config/.cache 2>/dev/null || true
""",
}


def session_candidates(session):
    """Binaries that would prove the desktop actually installed."""
    toks = [t for t in re.split(r"[^A-Za-z0-9_.+-]+", session) if t]
    drop = {"sh", "bash", "c", "exec", "session", "w", "start", "usr", "bin", "true"}
    out = []
    for t in toks:
        if t in drop or t.startswith("-") or t.isdigit():
            continue
        if t not in out:
            out.append(t)
    return out or ["true"]


def gen_install_sh(entry):
    rec = entry["recipe"]
    body = INSTALL_SH[rec["pm"]]
    verify = " ".join(session_candidates(rec["session"]))
    return """#!/bin/sh
set -eu
PKGS="%s"
VERIFY="%s"
echo ">> forge: building %s"
%s
ok=0
for b in $VERIFY; do
  if command -v "$b" >/dev/null 2>&1; then ok=1; echo ">> forge: found session binary $b"; fi
done
if [ "$ok" != "1" ]; then
  echo ">> forge: FATAL none of these session binaries installed: $VERIFY"
  exit 97
fi
echo ">> forge: desktop installed cleanly"
""" % (" ".join(rec["pkgs"].split()), verify, entry["name"], body.strip())


def gen_startwm(entry):
    rec = entry["recipe"]
    theme = rec.get("theme") or {}
    gtk = theme.get("gtk")
    icons = theme.get("icons")
    font = "Inter 10" if theme.get("gtk") == "Arc-Dark" else "Noto Sans 10"
    out = ["#!/usr/bin/env bash",
           "# generated by selkies-forge %s for %s" % (VERSION, entry["id"]),
           "setterm blank 0 2>/dev/null || true",
           "setterm powerdown 0 2>/dev/null || true",
           'export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/xdg-runtime-abc}"',
           'mkdir -p -m 700 "$XDG_RUNTIME_DIR" 2>/dev/null || true',
           'cfg="${HOME:-/config}"']
    for ev in rec.get("env", []):
        out.append("export %s" % ev)

    if gtk or icons:
        out += [
            'mkdir -p "$cfg/.config/gtk-3.0" "$cfg/.config/gtk-4.0" '
            '"$cfg/.config/xsettingsd" "$cfg/.config/autostart" 2>/dev/null || true',
            'if [ ! -f "$cfg/.config/gtk-3.0/settings.ini" ]; then',
            '  cat > "$cfg/.config/gtk-3.0/settings.ini" <<GTKEOF',
            '[Settings]',
            'gtk-theme-name=%s' % (gtk or "Adwaita"),
            'gtk-icon-theme-name=%s' % (icons or "Adwaita"),
            'gtk-font-name=%s' % font,
            'gtk-application-prefer-dark-theme=%d' % (1 if "dark" in (gtk or "").lower() else 0),
            'gtk-enable-animations=1',
            'GTKEOF',
            '  cp -f "$cfg/.config/gtk-3.0/settings.ini" '
            '"$cfg/.config/gtk-4.0/settings.ini" 2>/dev/null || true',
            'fi',
            'if [ ! -f "$cfg/.gtkrc-2.0" ]; then',
            '  printf \'gtk-theme-name="%s"\\ngtk-icon-theme-name="%s"\\ngtk-font-name="%s"\\n\' '
            '> "$cfg/.gtkrc-2.0"' % (gtk or "Adwaita", icons or "Adwaita", font),
            'fi',
            'if [ ! -f "$cfg/.config/xsettingsd/xsettingsd.conf" ]; then',
            '  cat > "$cfg/.config/xsettingsd/xsettingsd.conf" <<XSEOF',
            'Net/ThemeName "%s"' % (gtk or "Adwaita"),
            'Net/IconThemeName "%s"' % (icons or "Adwaita"),
            'Gtk/FontName "%s"' % font,
            'Gtk/EnableAnimations 1',
            'XSEOF',
            'fi',
        ]
        if entry.get("de") == "xfce":
            out += [
                'xfd="$cfg/.config/xfce4/xfconf/xfce-perchannel-xml"',
                'if [ ! -f "$xfd/xsettings.xml" ]; then',
                '  mkdir -p "$xfd" 2>/dev/null || true',
                '  cat > "$xfd/xsettings.xml" <<XFEOF',
                '<?xml version="1.0" encoding="UTF-8"?>',
                '<channel name="xsettings" version="1.0">',
                '  <property name="Net" type="empty">',
                '    <property name="ThemeName" type="string" value="%s"/>' % (gtk or "Adwaita"),
                '    <property name="IconThemeName" type="string" value="%s"/>' % (icons or "Adwaita"),
                '  </property>',
                '  <property name="Gtk" type="empty">',
                '    <property name="FontName" type="string" value="%s"/>' % font,
                '  </property>',
                '</channel>',
                'XFEOF',
                'fi',
            ]

    if theme.get("dock"):
        out += [
            'if [ ! -f "$cfg/.config/autostart/plank.desktop" ] && command -v plank >/dev/null 2>&1; then',
            '  mkdir -p "$cfg/.config/autostart" 2>/dev/null || true',
            '  printf \'[Desktop Entry]\\nType=Application\\nName=Plank\\nExec=plank\\n'
            'X-GNOME-Autostart-enabled=true\\n\' > "$cfg/.config/autostart/plank.desktop"',
            'fi',
            '(sleep 6; command -v plank >/dev/null 2>&1 && plank >/dev/null 2>&1 &) &',
        ]

    for line in rec.get("pre", []):
        out.append(line)

    if rec.get("bare"):
        term = rec.get("term", "xterm")
        # A bare window manager starts on a black root window: paint the forge
        # wallpaper (twice: some window managers paint over it as they start).
        out.append('(for d in 2 6; do sleep $d; command -v feh >/dev/null 2>&1 && '
                   'feh --no-fehbg --bg-fill /usr/local/share/forge/wallpaper.jpg 2>/dev/null; done) &')
        # Open a terminal, unless the seeded config (i3, bspwm) already opened one.
        out.append('(sleep 4; pgrep -u "$(id -u)" -x %s >/dev/null 2>&1 || '
                   '{ command -v %s >/dev/null 2>&1 && %s >/dev/null 2>&1; } &) &'
                   % (term, term, term))

    out.append(layer.supervised_session(rec["session"]))
    return "\n".join(out) + "\n"


def gen_dockerfile(entry):
    rec = entry["recipe"]
    inst = base64.b64encode(gen_install_sh(entry).encode()).decode()
    df = [
        "FROM %s" % rec["image"],
        'LABEL %s.entry="%s"' % (LABEL, entry["id"]),
        'LABEL %s.builder="selkies-forge %s"' % (LABEL, VERSION),
        'ENV TITLE="%s"' % entry["name"].replace('"', ""),
        "RUN printf '%%s' '%s' | base64 -d > /tmp/forge-install.sh \\\n"
        "    && chmod +x /tmp/forge-install.sh \\\n"
        "    && /tmp/forge-install.sh \\\n"
        "    && rm -f /tmp/forge-install.sh" % inst,
        "EXPOSE 3000 3001",
        "VOLUME /config",
    ]
    return "\n".join(df) + "\n"


def build_image_tag(entry):
    return "%s%s:latest" % (IPREFIX, entry["id"])
